const Locations = {};

Locations.US = [
	["New York City", "New York"],
	["Los Angeles", "California"],
	["Chicago", "Illinois"],
	["Houston", "Texas"],
	["Phoenix", "Arizona"],
	["Philadelphia", "Pennsylvania"],
	["San Antonio", "Texas"],
	["San Diego", "California"],
	["Dallas", "Texas"],
	["San Jose", "California"],
	["Austin", "Texas"],
	["Jacksonville", "Florida"],
	["Fort Worth", "Texas"],
	["Columbus", "Ohio"],
	["Charlotte", "North Carolina"],
	["San Francisco", "California"],
	["Indianapolis", "Indiana"],
	["Seattle", "Washington"],
	["Denver", "Colorado"],
	["Washington", "District of Columbia"],
	["Boston", "Massachusetts"],
	["El Paso", "Texas"],
	["Nashville", "Tennessee"],
	["Detroit", "Michigan"],
	["Oklahoma City", "Oklahoma"],
	["Portland", "Oregon"],
	["Las Vegas", "Nevada"],
	["Memphis", "Tennessee"],
	["Louisville", "Kentucky"],
	["Baltimore", "Maryland"],
	["Milwaukee", "Wisconsin"],
	["Albuquerque", "New Mexico"],
	["Tucson", "Arizona"],
	["Fresno", "California"],
	["Mesa", "Arizona"],
	["Sacramento", "California"],
	["Atlanta", "Georgia"],
	["Kansas City", "Missouri"],
	["Colorado Springs", "Colorado"],
	["Omaha", "Nebraska"],
	["Raleigh", "North Carolina"],
	["Miami", "Florida"],
	["Long Beach", "California"],
	["Virginia Beach", "Virginia"],
	["Oakland", "California"],
	["Minneapolis", "Minnesota"],
	["Tulsa", "Oklahoma"],
	["Tampa", "Florida"],
	["Arlington", "Texas"],
	["New Orleans", "Louisiana"],
	["Wichita", "Kansas"],
	["Bakersfield", "California"],
	["Cleveland", "Ohio"],
	["Aurora", "Colorado"],
	["Anaheim", "California"],
	["Santa Ana", "California"],
	["Riverside", "California"],
	["Corpus Christi", "Texas"],
	["Lexington", "Kentucky"],
	["Henderson", "Nevada"],
	["Stockton", "California"],
	["Saint Paul", "Minnesota"],
	["Cincinnati", "Ohio"],
	["St. Louis", "Missouri"],
	["Pittsburgh", "Pennsylvania"],
	["Greensboro", "North Carolina"],
	["Lincoln", "Nebraska"],
	["Plano", "Texas"],
	["Orlando", "Florida"],
	["Irvine", "California"],
	["Newark", "New Jersey"],
	["Durham", "North Carolina"],
	["Chula Vista", "California"],
	["Toledo", "Ohio"],
	["Fort Wayne", "Indiana"],
	["St. Petersburg", "Florida"],
	["Laredo", "Texas"],
	["Jersey City", "New Jersey"],
	["Chandler", "Arizona"],
	["Madison", "Wisconsin"],
	["Lubbock", "Texas"],
	["Scottsdale", "Arizona"],
	["Reno", "Nevada"],
	["Buffalo", "New York"],
	["Gilbert", "Arizona"],
	["Glendale", "Arizona"],
	["North Las Vegas", "Nevada"],
	["Winston–Salem", "North Carolina"],
	["Chesapeake", "Virginia"],
	["Norfolk", "Virginia"],
	["Fremont", "California"],
	["Garland", "Texas"],
	["Irving", "Texas"],
	["Hialeah", "Florida"],
	["Richmond", "Virginia"],
	["Boise", "Idaho"],
	["Spokane", "Washington"],
	["Baton Rouge", "Louisiana"],
	["Tacoma", "Washington"],
	["San Bernardino", "California"],
	["Modesto", "California"],
	["Fontana", "California"],
	["Des Moines", "Iowa"],
	["Moreno Valley", "California"],
	["Santa Clarita", "California"],
	["Fayetteville", "North Carolina"],
	["Birmingham", "Alabama"],
	["Oxnard", "California"],
	["Rochester", "New York"],
	["Port St. Lucie", "Florida"],
	["Grand Rapids", "Michigan"],
	["Huntsville", "Alabama"],
	["Salt Lake City", "Utah"],
	["Frisco", "Texas"],
	["Yonkers", "New York"],
	["Amarillo", "Texas"],
	["Glendale", "California"],
	["Huntington Beach", "California"],
	["McKinney", "Texas"],
	["Montgomery", "Alabama"],
	["Augusta", "Georgia"],
	["Aurora", "Illinois"],
	["Akron", "Ohio"],
	["Little Rock", "Arkansas"],
	["Tempe", "Arizona"],
	["Columbus", "Georgia"],
	["Overland Park", "Kansas"],
	["Grand Prairie", "Texas"],
	["Tallahassee", "Florida"],
	["Cape Coral", "Florida"],
	["Mobile", "Alabama"],
	["Knoxville", "Tennessee"],
	["Shreveport", "Louisiana"],
	["Worcester", "Massachusetts"],
	["Ontario", "California"],
	["Vancouver", "Washington"],
	["Sioux Falls", "South Dakota"],
	["Chattanooga", "Tennessee"],
	["Brownsville", "Texas"],
	["Fort Lauderdale", "Florida"],
	["Providence", "Rhode Island"],
	["Newport News", "Virginia"],
	["Rancho Cucamonga", "California"],
	["Santa Rosa", "California"],
	["Peoria", "Arizona"],
	["Oceanside", "California"],
	["Elk Grove", "California"],
	["Salem", "Oregon"],
	["Pembroke Pines", "Florida"],
	["Eugene", "Oregon"],
	["Garden Grove", "California"],
	["Cary", "North Carolina"],
	["Fort Collins", "Colorado"],
	["Corona", "California"],
	["Springfield", "Missouri"],
	["Jackson", "Mississippi"],
	["Alexandria", "Virginia"],
	["Hayward", "California"],
	["Clarksville", "Tennessee"],
	["Lakewood", "Colorado"],
	["Lancaster", "California"],
	["Salinas", "California"],
	["Palmdale", "California"],
	["Hollywood", "Florida"],
	["Springfield", "Massachusetts"],
	["Macon", "Georgia"],
	["Kansas City", "Kansas"],
	["Sunnyvale", "California"],
	["Pomona", "California"],
	["Killeen", "Texas"],
	["Escondido", "California"],
	["Pasadena", "Texas"],
	["Naperville", "Illinois"],
	["Bellevue", "Washington"],
	["Joliet", "Illinois"],
	["Murfreesboro", "Tennessee"],
	["Midland", "Texas"],
	["Rockford", "Illinois"],
	["Paterson", "New Jersey"],
	["Savannah", "Georgia"],
	["Bridgeport", "Connecticut"],
	["Torrance", "California"],
	["McAllen", "Texas"],
	["Syracuse", "New York"],
	["Surprise", "Arizona"],
	["Denton", "Texas"],
	["Roseville", "California"],
	["Thornton", "Colorado"],
	["Miramar", "Florida"],
	["Pasadena", "California"],
	["Mesquite", "Texas"],
	["Olathe", "Kansas"],
	["Dayton", "Ohio"],
	["Carrollton", "Texas"],
	["Waco", "Texas"],
	["Orange", "California"],
	["Fullerton", "California"],
	["Charleston", "South Carolina"],
	["West Valley City", "Utah"],
	["Visalia", "California"],
	["Hampton", "Virginia"],
	["Gainesville", "Florida"],
	["Warren", "Michigan"],
	["Coral Springs", "Florida"],
	["Cedar Rapids", "Iowa"],
	["Round Rock", "Texas"],
	["Sterling Heights", "Michigan"],
	["Kent", "Washington"],
	["Columbia", "South Carolina"],
	["Santa Clara", "California"],
	["New Haven", "Connecticut"],
	["Stamford", "Connecticut"],
	["Concord", "California"],
	["Elizabeth", "New Jersey"],
	["Athens", "Georgia"],
	["Thousand Oaks", "California"],
	["Lafayette", "Louisiana"],
	["Simi Valley", "California"],
	["Topeka", "Kansas"],
	["Norman", "Oklahoma"],
	["Fargo", "North Dakota"],
	["Wilmington", "North Carolina"],
	["Abilene", "Texas"],
	["Odessa", "Texas"],
	["Columbia", "Missouri"],
	["Pearland", "Texas"],
	["Victorville", "California"],
	["Hartford", "Connecticut"],
	["Vallejo", "California"],
	["Allentown", "Pennsylvania"],
	["Berkeley", "California"],
	["Richardson", "Texas"],
	["Arvada", "Colorado"],
	["Ann Arbor", "Michigan"],
	["Rochester", "Minnesota"],
	["Cambridge", "Massachusetts"],
	["Sugar Land", "Texas"],
	["Lansing", "Michigan"],
	["Evansville", "Indiana"],
	["College Station", "Texas"],
	["Fairfield", "California"],
	["Clearwater", "Florida"],
	["Beaumont", "Texas"],
	["Independence", "Missouri"],
	["Provo", "Utah"],
	["West Jordan", "Utah"],
	["Murrieta", "California"],
	["Palm Bay", "Florida"],
	["El Monte", "California"],
	["Carlsbad", "California"],
	["Temecula", "California"],
	["Clovis", "California"],
	["Springfield", "Illinois"],
	["Meridian", "Idaho"],
	["Westminster", "Colorado"],
	["Costa Mesa", "California"],
	["High Point", "North Carolina"],
	["Manchester", "New Hampshire"],
	["Pueblo", "Colorado"],
	["Lakeland", "Florida"],
	["Pompano Beach", "Florida"],
	["West Palm Beach", "Florida"],
	["Antioch", "California"],
	["Everett", "Washington"],
	["Downey", "California"],
	["Lowell", "Massachusetts"],
	["Centennial", "Colorado"],
	["Elgin", "Illinois"],
	["Richmond", "California"],
	["Peoria", "Illinois"],
	["Broken Arrow", "Oklahoma"],
	["Miami Gardens", "Florida"],
	["Billings", "Montana"],
	["Jurupa Valley", "California"],
	["Sandy Springs", "Georgia"],
	["Gresham", "Oregon"],
	["Lewisville", "Texas"],
	["Hillsboro", "Oregon"],
	["Ventura", "California"],
	["Greeley", "Colorado"],
	["Inglewood", "California"],
	["Waterbury", "Connecticut"],
	["League City", "Texas"],
	["Santa Maria", "California"],
	["Tyler", "Texas"],
	["Davie", "Florida"],
	["Lakewood", "New Jersey"],
	["Daly City", "California"],
	["Boulder", "Colorado"],
	["Allen", "Texas"],
	["West Covina", "California"],
	["Sparks", "Nevada"],
	["Wichita Falls", "Texas"],
	["Green Bay", "Wisconsin"],
	["San Mateo", "California"],
	["Norwalk", "California"],
	["Rialto", "California"],
	["Las Cruces", "New Mexico"],
	["Chico", "California"],
	["El Cajon", "California"],
	["Burbank", "California"],
	["South Bend", "Indiana"],
	["Renton", "Washington"],
	["Vista", "California"],
	["Davenport", "Iowa"],
	["Edinburg", "Texas"],
	["Tuscaloosa", "Alabama"],
	["Carmel", "Indiana"],
	["Spokane Valley", "Washington"],
	["San Angelo", "Texas"],
	["Vacaville", "California"],
	["Clinton", "Michigan"],
	["Bend", "Oregon"],
	["Woodbridge", "New Jersey"],
	["Lexington-Fayette", "Kentucky"],
	["St. Paul", "Minnesota"],
	["North Hempstead", "New York"],
	["New York", "New York"],
	["Huntington", "New York"],
	["Nashville-Davidson", "Tennessee"],
	["Arlington", "Virginia"],
];

Locations.DE = [
	["Berlin", "Berlin"],
	["Hamburg", "Hamburg"],
	["Munich", "Bavaria"],
	["Cologne", "North Rhine-Westphalia"],
	["Frankfurt", "Hesse"],
	["Stuttgart", "Baden-Württemberg"],
	["Düsseldorf", "North Rhine-Westphalia"],
	["Dortmund", "North Rhine-Westphalia"],
	["Essen", "North Rhine-Westphalia"],
	["Leipzig", "Saxony"],
	["Bremen", "Bremen"],
	["Dresden", "Saxony"],
	["Hanover", "Lower Saxony"],
	["Nuremberg", "Bavaria"],
	["Duisburg", "North Rhine-Westphalia"],
	["Bochum", "North Rhine-Westphalia"],
	["Wuppertal", "North Rhine-Westphalia"],
	["Bielefeld", "North Rhine-Westphalia"],
	["Bonn", "North Rhine-Westphalia"],
	["Münster", "North Rhine-Westphalia"],
	["Karlsruhe", "Baden-Württemberg"],
	["Mannheim", "Baden-Württemberg"],
	["Augsburg", "Bavaria"],
	["Wiesbaden", "Hesse"],
	["Gelsenkirchen", "North Rhine-Westphalia"],
	["Mönchengladbach", "North Rhine-Westphalia"],
	["Braunschweig", "Lower Saxony"],
	["Chemnitz", "Saxony"],
	["Kiel", "Schleswig-Holstein"],
	["Aachen", "North Rhine-Westphalia"],
	["Halle", "Saxony-Anhalt"],
	["Magdeburg", "Saxony-Anhalt"],
	["Freiburg im Breisgau", "Baden-Württemberg"],
	["Krefeld", "North Rhine-Westphalia"],
	["Lübeck", "Schleswig-Holstein"],
	["Oberhausen", "North Rhine-Westphalia"],
	["Erfurt", "Thuringia"],
	["Mainz", "Rhineland-Palatinate"],
	["Rostock", "Mecklenburg-Vorpommern"],
	["Kassel", "Hesse"],
	["Hagen", "North Rhine-Westphalia"],
	["Hamm", "North Rhine-Westphalia"],
	["Saarbrücken", "Saarland"],
	["Mülheim an der Ruhr", "North Rhine-Westphalia"],
	["Potsdam", "Brandenburg"],
	["Ludwigshafen am Rhein", "Rhineland-Palatinate"],
	["Oldenburg", "Lower Saxony"],
	["Leverkusen", "North Rhine-Westphalia"],
	["Osnabrück", "Lower Saxony"],
	["Solingen", "North Rhine-Westphalia"],
	["Heidelberg", "Baden-Württemberg"],
	["Herne", "North Rhine-Westphalia"],
	["Neuss", "North Rhine-Westphalia"],
	["Darmstadt", "Hesse"],
	["Paderborn", "North Rhine-Westphalia"],
	["Regensburg", "Bavaria"],
	["Ingolstadt", "Bavaria"],
	["Würzburg", "Bavaria"],
	["Fürth", "Bavaria"],
	["Wolfsburg", "Lower Saxony"],
	["Offenbach am Main", "Hesse"],
	["Ulm", "Baden-Württemberg"],
	["Heilbronn", "Baden-Württemberg"],
	["Pforzheim", "Baden-Württemberg"],
	["Göttingen", "Lower Saxony"],
	["Bottrop", "North Rhine-Westphalia"],
	["Trier", "Rhineland-Palatinate"],
	["Recklinghausen", "North Rhine-Westphalia"],
	["Reutlingen", "Baden-Württemberg"],
	["Bremerhaven", "Bremen"],
	["Koblenz", "Rhineland-Palatinate"],
	["Bergisch Gladbach", "North Rhine-Westphalia"],
	["Jena", "Thuringia"],
	["Remscheid", "North Rhine-Westphalia"],
	["Erlangen", "Bavaria"],
	["Moers", "North Rhine-Westphalia"],
	["Siegen", "North Rhine-Westphalia"],
	["Hildesheim", "Lower Saxony"],
	["Salzgitter", "Lower Saxony"],
];

Locations.FR = [
	["Paris", "Île-de-France"],
	["Marseille", "Provence-Alpes-Côte d'Azur"],
	["Lyon", "Auvergne-Rhône-Alpes"],
	["Toulouse", "Occitanie"],
	["Nice", "Provence-Alpes-Côte d'Azur"],
	["Nantes", "Pays de la Loire"],
	["Strasbourg", "Grand Est"],
	["Montpellier", "Occitanie"],
	["Bordeaux", "Nouvelle-Aquitaine"],
	["Lille", "Hauts-de-France"],
	["Rennes", "Brittany"],
	["Reims", "Grand Est"],
	["Le Havre", "Normandy"],
	["Saint-Étienne", "Auvergne-Rhône-Alpes"],
	["Toulon", "Provence-Alpes-Côte d'Azur"],
	["Grenoble", "Auvergne-Rhône-Alpes"],
	["Dijon", "Bourgogne-Franche-Comté"],
	["Nîmes", "Occitanie"],
	["Angers", "Pays de la Loire"],
	["Villeurbanne", "Auvergne-Rhône-Alpes"],
	["Le Mans", "Pays de la Loire"],
	["Saint-Denis", "Réunion"],
	["Aix-en-Provence", "Provence-Alpes-Côte d'Azur"],
	["Clermont-Ferrand", "Auvergne-Rhône-Alpes"],
	["Brest", "Brittany"],
	["Limoges", "Nouvelle-Aquitaine"],
	["Tours", "Centre-Val de Loire"],
	["Amiens", "Hauts-de-France"],
	["Perpignan", "Occitanie"],
	["Metz", "Grand Est"],
	["Besançon", "Bourgogne-Franche-Comté"],
	["Boulogne-Billancourt", "Île-de-France"],
	["Orléans", "Centre-Val de Loire"],
	["Mulhouse", "Grand Est"],
	["Rouen", "Normandy"],
	["Saint-Denis", "Île-de-France"],
	["Caen", "Normandy"],
	["Argenteuil", "Île-de-France"],
	["Saint-Paul", "Réunion"],
	["Montreuil", "Île-de-France"],
	["Nancy", "Grand Est"],
	["Roubaix", "Hauts-de-France"],
	["Tourcoing", "Hauts-de-France"],
	["Nanterre", "Île-de-France"],
	["Avignon", "Provence-Alpes-Côte d'Azur"],
	["Vitry-sur-Seine", "Île-de-France"],
	["Créteil", "Île-de-France"],
	["Dunkirk", "Hauts-de-France"],
	["Poitiers", "Nouvelle-Aquitaine"],
	["Asnières-sur-Seine", "Île-de-France"],
	["Courbevoie", "Île-de-France"],
	["Versailles", "Île-de-France"],
	["Colombes", "Île-de-France"],
	["Fort-de-France", "Martinique"],
	["Aulnay-sous-Bois", "Île-de-France"],
	["Saint-Pierre", "Réunion"],
	["Rueil-Malmaison", "Île-de-France"],
	["Pau", "Nouvelle-Aquitaine"],
	["Aubervilliers", "Île-de-France"],
	["Le Tampon", "Réunion"],
	["Champigny-sur-Marne", "Île-de-France"],
	["Antibes", "Provence-Alpes-Côte d'Azur"],
	["Béziers", "Occitanie"],
	["La Rochelle", "Nouvelle-Aquitaine"],
	["Saint-Maur-des-Fossés", "Île-de-France"],
	["Cannes", "Provence-Alpes-Côte d'Azur"],
	["Calais", "Hauts-de-France"],
	["Saint-Nazaire", "Pays de la Loire"],
	["Mérignac", "Nouvelle-Aquitaine"],
	["Drancy", "Île-de-France"],
	["Colmar", "Grand Est"],
	["Ajaccio", "Corsica"],
	["Bourges", "Centre-Val de Loire"],
	["Issy-les-Moulineaux", "Île-de-France"],
	["Levallois-Perret", "Île-de-France"],
	["La Seyne-sur-Mer", "Provence-Alpes-Côte d'Azur"],
	["Quimper", "Brittany"],
	["Noisy-le-Grand", "Île-de-France"],
	["Villeneuve-d'Ascq", "Hauts-de-France"],
	["Neuilly-sur-Seine", "Île-de-France"],
	["Valence", "Auvergne-Rhône-Alpes"],
	["Antony", "Île-de-France"],
	["Cergy", "Île-de-France"],
	["Vénissieux", "Auvergne-Rhône-Alpes"],
	["Pessac", "Nouvelle-Aquitaine"],
	["Troyes", "Grand Est"],
	["Clichy", "Île-de-France"],
	["Ivry-sur-Seine", "Île-de-France"],
	["Chambéry", "Auvergne-Rhône-Alpes"],
	["Lorient", "Brittany"],
	["Les Abymes", "Guadeloupe"],
	["Montauban", "Occitanie"],
	["Sarcelles", "Île-de-France"],
	["Niort", "Nouvelle-Aquitaine"],
	["Villejuif", "Île-de-France"],
	["Saint-André", "Réunion"],
	["Hyères", "Provence-Alpes-Côte d'Azur"],
	["Saint-Quentin", "Hauts-de-France"],
	["Beauvais", "Hauts-de-France"],
	["Épinay-sur-Seine", "Île-de-France"],
	["Cayenne", "French Guiana"],
	["Maisons-Alfort", "Île-de-France"],
	["Cholet", "Pays de la Loire"],
	["Meaux", "Île-de-France"],
	["Chelles", "Île-de-France"],
	["Pantin", "Île-de-France"],
	["Évry", "Île-de-France"],
	["Fontenay-sous-Bois", "Île-de-France"],
	["Fréjus", "Provence-Alpes-Côte d'Azur"],
	["Vannes", "Brittany"],
	["Bondy", "Île-de-France"],
	["Le Blanc-Mesnil", "Île-de-France"],
	["La Roche-sur-Yon", "Pays de la Loire"],
	["Saint-Louis", "Réunion"],
	["Arles", "Provence-Alpes-Côte d'Azur"],
	["Clamart", "Île-de-France"],
	["Narbonne", "Occitanie"],
	["Annecy", "Auvergne-Rhône-Alpes"],
	["Sartrouville", "Île-de-France"],
	["Grasse", "Provence-Alpes-Côte d'Azur"],
	["Laval", "Pays de la Loire"],
	["Belfort", "Bourgogne-Franche-Comté"],
	["Bobigny", "Île-de-France"],
	["Évreux", "Normandy"],
	["Vincennes", "Île-de-France"],
	["Montrouge", "Île-de-France"],
	["Sevran", "Île-de-France"],
	["Albi", "Occitanie"],
	["Charleville-Mézières", "Grand Est"],
	["Suresnes", "Île-de-France"],
	["Martigues", "Provence-Alpes-Côte d'Azur"],
	["Corbeil-Essonnes", "Île-de-France"],
	["Saint-Ouen", "Île-de-France"],
	["Bayonne", "Nouvelle-Aquitaine"],
	["Cagnes-sur-Mer", "Provence-Alpes-Côte d'Azur"],
	["Brive-la-Gaillarde", "Nouvelle-Aquitaine"],
	["Carcassonne", "Occitanie"],
	["Massy", "Île-de-France"],
	["Blois", "Centre-Val de Loire"],
	["Aubagne", "Provence-Alpes-Côte d'Azur"],
	["Saint-Brieuc", "Brittany"],
	["Châteauroux", "Centre-Val de Loire"],
	["Chalon-sur-Saône", "Bourgogne-Franche-Comté"],
	["Mantes-la-Jolie", "Île-de-France"],
	["Meudon", "Île-de-France"],
	["Saint-Malo", "Brittany"],
	["Châlons-en-Champagne", "Grand Est"],
	["Alfortville", "Île-de-France"],
	["Sète", "Occitanie"],
	["Salon-de-Provence", "Provence-Alpes-Côte d'Azur"],
	["Vaulx-en-Velin", "Auvergne-Rhône-Alpes"],
	["Puteaux", "Île-de-France"],
	["Rosny-sous-Bois", "Île-de-France"],
	["Saint-Herblain", "Pays de la Loire"],
	["Gennevilliers", "Île-de-France"],
	["Le Cannet", "Provence-Alpes-Côte d'Azur"],
	["Livry-Gargan", "Île-de-France"],
	["Saint-Priest", "Auvergne-Rhône-Alpes"],
	["Istres", "Provence-Alpes-Côte d'Azur"],
	["Valenciennes", "Hauts-de-France"],
	["Choisy-le-Roi", "Île-de-France"],
	["Caluire-et-Cuire", "Auvergne-Rhône-Alpes"],
	["Boulogne-sur-Mer", "Hauts-de-France"],
	["Bastia", "Corsica"],
	["Angoulême", "Nouvelle-Aquitaine"],
	["Garges-lès-Gonesse", "Île-de-France"],
	["Castres", "Occitanie"],
	["Thionville", "Grand Est"],
	["Wattrelos", "Hauts-de-France"],
	["Talence", "Nouvelle-Aquitaine"],
	["Saint-Laurent-du-Maroni", "French Guiana"],
	["Douai", "Hauts-de-France"],
	["Noisy-le-Sec", "Île-de-France"],
	["Tarbes", "Occitanie"],
	["Arras", "Hauts-de-France"],
	["Alès", "Occitanie"],
	["La Courneuve", "Île-de-France"],
	["Bourg-en-Bresse", "Auvergne-Rhône-Alpes"],
	["Compiègne", "Hauts-de-France"],
	["Gap", "Provence-Alpes-Côte d'Azur"],
	["Melun", "Île-de-France"],
	["Le Lamentin", "Martinique"],
	["Rezé", "Pays de la Loire"],
	["Saint-Germain-en-Laye", "Île-de-France"],
	["Marcq-en-Barœul", "Hauts-de-France"],
	["Gagny", "Île-de-France"],
	["Anglet", "Nouvelle-Aquitaine"],
	["Draguignan", "Provence-Alpes-Côte d'Azur"],
	["Chartres", "Centre-Val de Loire"],
	["Bron", "Auvergne-Rhône-Alpes"],
	["Bagneux", "Île-de-France"],
	["Colomiers", "Occitanie"],
	["Saint-Martin-d'Hères", "Auvergne-Rhône-Alpes"],
	["Pontault-Combault", "Île-de-France"],
	["Montluçon", "Auvergne-Rhône-Alpes"],
	["Joué-lès-Tours", "Centre-Val de Loire"],
	["Saint-Joseph", "Réunion"],
	["Poissy", "Île-de-France"],
	["Savigny-sur-Orge", "Île-de-France"],
	["Cherbourg-Octeville", "Normandy"],
	["Montélimar", "Auvergne-Rhône-Alpes"],
	["Villefranche-sur-Saône", "Auvergne-Rhône-Alpes"],
	["Stains", "Île-de-France"],
	["Saint-Benoît", "Réunion"],
	["Bagnolet", "Île-de-France"],
	["Châtillon", "Île-de-France"],
	["Le Port", "Réunion"],
	["Sainte-Geneviève-des-Bois", "Île-de-France"],
	["Échirolles", "Auvergne-Rhône-Alpes"],
	["Roanne", "Auvergne-Rhône-Alpes"],
	["Villepinte", "Île-de-France"],
	["Saint-Chamond", "Auvergne-Rhône-Alpes"],
	["Conflans-Sainte-Honorine", "Île-de-France"],
	["Auxerre", "Bourgogne-Franche-Comté"],
	["Nevers", "Bourgogne-Franche-Comté"],
	["Neuilly-sur-Marne", "Île-de-France"],
	["La Ciotat", "Provence-Alpes-Côte d'Azur"],
	["Tremblay-en-France", "Île-de-France"],
	["Thonon-les-Bains", "Auvergne-Rhône-Alpes"],
	["Vitrolles", "Provence-Alpes-Côte d'Azur"],
	["Haguenau", "Grand Est"],
	["Six-Fours-les-Plages", "Provence-Alpes-Côte d'Azur"],
	["Agen", "Nouvelle-Aquitaine"],
	["Creil", "Hauts-de-France"],
	["Annemasse", "Auvergne-Rhône-Alpes"],
	["Saint-Raphaël", "Provence-Alpes-Côte d'Azur"],
	["Marignane", "Provence-Alpes-Côte d'Azur"],
	["Romans-sur-Isère", "Auvergne-Rhône-Alpes"],
	["Montigny-le-Bretonneux", "Île-de-France"],
	["Le Perreux-sur-Marne", "Île-de-France"],
	["Franconville", "Île-de-France"],
	["Mâcon", "Bourgogne-Franche-Comté"],
	["Saint-Leu", "Réunion"],
	["Cambrai", "Hauts-de-France"],
	["Châtenay-Malabry", "Île-de-France"],
	["Sainte-Marie", "Réunion"],
	["Villeneuve-Saint-Georges", "Île-de-France"],
	["Houilles", "Île-de-France"],
	["Épinal", "Grand Est"],
	["Lens", "Hauts-de-France"],
	["Liévin", "Hauts-de-France"],
	["Les Mureaux", "Île-de-France"],
	["Schiltigheim", "Grand Est"],
	["La Possession", "Réunion"],
	["Meyzieu", "Auvergne-Rhône-Alpes"],
	["Dreux", "Centre-Val de Loire"],
	["Nogent-sur-Marne", "Île-de-France"],
	["Plaisir", "Île-de-France"],
	["Mont-de-Marsan", "Nouvelle-Aquitaine"],
	["Palaiseau", "Île-de-France"],
	["Châtellerault", "Nouvelle-Aquitaine"],
	["Goussainville", "Île-de-France"],
	["L'Haÿ-les-Roses", "Île-de-France"],
	["Viry-Châtillon", "Île-de-France"],
	["Vigneux-sur-Seine", "Île-de-France"],
	["Chatou", "Île-de-France"],
	["Trappes", "Île-de-France"],
	["Clichy-sous-Bois", "Île-de-France"],
	["Rillieux-la-Pape", "Auvergne-Rhône-Alpes"],
	["Villenave-d'Ornon", "Nouvelle-Aquitaine"],
	["Maubeuge", "Hauts-de-France"],
	["Charenton-le-Pont", "Île-de-France"],
	["Malakoff", "Île-de-France"],
	["Matoury", "French Guiana"],
	["Dieppe", "Normandy"],
	["Athis-Mons", "Île-de-France"],
	["Savigny-le-Temple", "Île-de-France"],
	["Périgueux", "Nouvelle-Aquitaine"],
	["Baie-Mahault", "Guadeloupe"],
	["Vandoeuvre-lès-Nancy", "Grand Est"],
	["Pontoise", "Île-de-France"],
	["Aix-les-Bains", "Auvergne-Rhône-Alpes"],
	["Cachan", "Île-de-France"],
	["Vienne", "Auvergne-Rhône-Alpes"],
	["Thiais", "Île-de-France"],
	["Orange", "Provence-Alpes-Côte d'Azur"],
	["Saint-Médard-en-Jalles", "Nouvelle-Aquitaine"],
	["Villemomble", "Île-de-France"],
	["Saint-Cloud", "Île-de-France"],
	["Saint-Laurent-du-Var", "Provence-Alpes-Côte d'Azur"],
	["Yerres", "Île-de-France"],
	["Saint-Étienne-du-Rouvray", "Normandy"],
	["Sotteville-lès-Rouen", "Normandy"],
	["Draveil", "Île-de-France"],
	["Le Chesnay", "Île-de-France"],
	["Bois-Colombes", "Île-de-France"],
	["Le Plessis-Robinson", "Île-de-France"],
	["La Garenne-Colombes", "Île-de-France"],
	["Lambersart", "Hauts-de-France"],
	["Soissons", "Hauts-de-France"],
	["Pierrefitte-sur-Seine", "Île-de-France"],
	["Carpentras", "Provence-Alpes-Côte d'Azur"],
	["Villiers-sur-Marne", "Île-de-France"],
	["Vanves", "Île-de-France"],
	["Menton", "Provence-Alpes-Côte d'Azur"],
	["Bergerac", "Nouvelle-Aquitaine"],
	["Ermont", "Île-de-France"],
	["Bezons", "Île-de-France"],
	["Grigny", "Île-de-France"],
	["Guyancourt", "Île-de-France"],
	["Saumur", "Pays de la Loire"],
	["Herblay", "Île-de-France"],
	["Ris-Orangis", "Île-de-France"],
	["Villiers-le-Bel", "Île-de-France"],
	["Bourgoin-Jallieu", "Auvergne-Rhône-Alpes"],
	["Vierzon", "Centre-Val de Loire"],
	["Le Gosier", "Guadeloupe"],
	["Décines-Charpieu", "Auvergne-Rhône-Alpes"],
	["Hénin-Beaumont", "Hauts-de-France"],
	["Fresnes", "Île-de-France"],
	["Aurillac", "Auvergne-Rhône-Alpes"],
	["Sannois", "Île-de-France"],
	["Vallauris", "Provence-Alpes-Côte d'Azur"],
	["Illkirch-Graffenstaden", "Grand Est"],
	["Alençon", "Normandy"],
	["Élancourt", "Île-de-France"],
	["Tournefeuille", "Occitanie"],
	["Bègles", "Nouvelle-Aquitaine"],
	["Gonesse", "Île-de-France"],
	["Oullins", "Auvergne-Rhône-Alpes"],
	["Brunoy", "Île-de-France"],
	["Taverny", "Île-de-France"],
	["Armentières", "Hauts-de-France"],
	["Montfermeil", "Île-de-France"],
	["Rambouillet", "Île-de-France"],
	["Villeparisis", "Île-de-France"],
	["Le Kremlin-Bicêtre", "Île-de-France"],
	["Sucy-en-Brie", "Île-de-France"],
	["Kourou", "French Guiana"],
	["Montbéliard", "Bourgogne-Franche-Comté"],
	["Romainville", "Île-de-France"],
	["Cavaillon", "Provence-Alpes-Côte d'Azur"],
	["Saint-Dizier", "Grand Est"],
	["Brétigny-sur-Orge", "Île-de-France"],
	["Saint-Sébastien-sur-Loire", "Pays de la Loire"],
	["Saintes", "Nouvelle-Aquitaine"],
	["La Teste-de-Buch", "Nouvelle-Aquitaine"],
	["Villeneuve-la-Garenne", "Île-de-France"],
	["Béthune", "Hauts-de-France"],
	["Bussy-Saint-Georges", "Île-de-France"],
	["Vichy", "Auvergne-Rhône-Alpes"],
	["La Garde", "Provence-Alpes-Côte d'Azur"],
	["Agde", "Occitanie"],
	["Laon", "Hauts-de-France"],
	["Sens", "Bourgogne-Franche-Comté"],
];

Locations.NL = [
	["Emmen", "Drenthe"],
	["Assen", "Drenthe"],
	["Leeuwarden", "Friesland"],
	["Súdwest-Fryslân", "Friesland"],
	["Smallingerland", "Friesland"],
	["Groningen", "Groningen"],
	["Amsterdam", "North Holland"],
	["Rotterdam", "South Holland"],
	["Utrecht", "Utrecht"],
	["Eindhoven", "North Brabant"],
	["Tilburg", "North Brabant"],
	["Almere", "Flevoland"],
	["Breda", "North Brabant"],
	["Nijmegen", "Gelderland"],
	["Apeldoorn", "Gelderland"],
	["Haarlem", "North Holland"],
	["Arnhem", "Gelderland"],
	["Enschede", "Overijssel"],
	["Amersfoort", "Utrecht"],
	["Zaanstad", "North Holland"],
	["Zwolle", "Overijssel"],
	["Leiden", "South Holland"],
];

Locations.GB = [
	["Haringey", "Greater London"],
	["Lancaster", "Lancashire"],
	["Islington", "Greater London"],
	["Coventry", "West Midlands"],
	["Bury", "Greater Manchester"],
	["Basildon", "Essex"],
	["Lambeth", "Greater London"],
	["Greenwich", "Greater London"],
	["Preston", "Lancashire"],
	["Croydon", "Greater London"],
	["Merton", "Greater London"],
	["Newham", "Greater London"],
	["Ashford", "Kent"],
	["Southwark", "Greater London"],
	["Redbridge", "Greater London"],
	["Wakefield", "West Yorkshire"],
	["Hillingdon", "Greater London"],
	["Chelmsford", "Essex"],
	["Bolton", "Greater Manchester"],
	["Harrow", "Greater London"],
	["Leeds", "West Yorkshire"],
	["Bromley", "Greater London"],
	["Ealing", "Greater London"],
	["Sutton", "Greater London"],
	["Blackburn", "Lancashire"],
	["Southampton", "Hampshire"],
	["Wolverhampton", "West Midlands"],
	["Rochdale", "Greater Manchester"],
	["Portsmouth", "Hampshire"],
	["Lewisham", "Greater London"],
	["Colchester", "Essex"],
	["Basingstoke", "Hampshire"],
	["Oldham", "Greater Manchester"],
	["Canterbury", "Kent"],
	["Enfield", "Greater London"],
	["Lowestoft", "Suffolk"],
	["Barnet", "Greater London"],
	["Birmingham", "West Midlands"],
	["Bradford", "West Yorkshire"],
	["Ipswich", "Suffolk"],
	["Gosport", "Hampshire"],
	["Brent", "Greater London"],
	["Dover", "Kent"],
	["Haverhill", "Suffolk"],
	["Hackney", "Greater London"],
	["Manchester", "Greater Manchester"],
	["Wandsworth", "Greater London"],
	["Camden", "Greater London"],
	["Havering", "Greater London"],
	["Hounslow", "Greater London"],
	["Bexley", "Greater London"],
	["Westminster", "Greater London"],
	["Blackpool", "Lancashire"],
];
